---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rvk-apps-nl-production
  namespace: default
spec:
  secretName: rvk-apps-nl-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.rvk-apps.nl"
  dnsNames:
  - "rvk-apps.nl"
  - "*.rvk-apps.nl"